# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation
# Still in development, subject to change without notice!!

language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML

install: 
    - cd
    
    # Install OMV
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

    # Install pyNeuroML
    - pip install git+https://github.com/NeuroML/pyNeuroML.git

    - cd $TRAVIS_BUILD_DIR

script:
    - cd ./NeuroML2/
    - pynml-channelanalysis -temperature 34   -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev 50 -norun  ./ca_boyle.channel.nml
    - pynml-channelanalysis -temperature 34   -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev -55 -norun  ./k_fast.channel.nml
    - pynml-channelanalysis -temperature 34   -minV -55  -maxV 80  -duration 600  -clampBaseVoltage -55  -clampDuration 580  -stepTargetVoltage 10  -erev -55 -norun  ./k_slow.channel.nml
    - omv all -V
    - pynml LEMS_Test_ca_boyle.xml -nogui    
    - pynml LEMS_Test_k_fast.xml -nogui
    - pynml LEMS_Test_k_slow.xml -nogui
    
    
